question_data = [
    # Each question is represented as a dictionary
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The average woman is 5 inches/13 centimeters shorter than the average man.",
     "correct_answer": "True", "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Kissing someone for one minute burns about 2 calories.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Coca-Colas original colour was green.",
     "correct_answer": "False", "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The bikini is named after the Bikini Atoll, an island where the United States conducted "
                 "tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Fast food restaurant chains Carls Jr. and Hardees are owned by the same company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Haggis is traditionally ate on Burns Night.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Furby was released in 1998.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Cucumbers are usually more than 90% water.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo is a grammatically correct sentence.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The French word for glass is glace.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The scientific name for the Southern Lights is Aurora Australis?",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "You are allowed to sell your soul on eBay.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "There are 86400 seconds in a day.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Albert Einstein had trouble with mathematics when he was in school.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Typewriter is the longest word that can be typed using only the first row on a QWERTY keyboard.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The French word to travel is Travail",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},

    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The sum of all the numbers on a roulette wheel is 666.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
